
version: '3.7'
services:
  mongodb_container:
    container_name: lsd-mongo
    networks:
      - docker_default
    image: mongo:4.0.4
    ports:
      - 10327:10327 
    volumes:
      - /home/data/lsdshop/mongo:/data/db
networks:
  docker_default:
    external: true

