version: '3.6'
services:
  nc-clientip-lsd:
     labels:
        - com.docker.stack.namespace=lsd
     ports:
      #   - '10312:8000'
        - '10483:10383'
     environment:
        - 'SPRING_PROFILES_ACTIVE=dev,docker'
        - 'JAVA_OPTS=-Xmx512m
-Dspring.cloud.config.uri=http://lsd-config:10390
-Dfluentd.host=lsd-fluentd -Dfluentd.port=10326'
        - 'WAIT_FOR=lsd-db:10332 lsd-config:10390 lsd-auth:10384
lsd-idp:10385'
        - HEALTH_CONFIG_ENABLED=true
     container_name: lsd-clientip
     image: 'registry.docker.hub/lsd-shop/nc-clientipservice-lsd'
     volumes:
         - /etc/localtime:/etc/timezone:ro
     networks:    
       - docker_default
networks:
  docker_default:
    external: true

